# -*- coding: utf-8 -*-

"""
/***************************************************************************
 OpenWeather
                                 A QGIS plugin
 Downloading Weather Data From OpenWeather API
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2022-02-17
        copyright            : (C) 2022 by Htet Arkar Soe
        email                : htetarkar.env.2016@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

__author__ = 'Htet Arkar Soe'
__date__ = '2022-02-17'
__copyright__ = '(C) 2022 by Htet Arkar Soe'

# This will get replaced with a git SHA1 when you do a git archive

__revision__ = '$Format:%H$'

import os
import sys
import inspect
from qgis.PyQt.QtWidgets import QAction
from qgis.PyQt.QtGui import QIcon,QDesktopServices
from qgis.PyQt.QtCore import QSettings, QTranslator, QCoreApplication, QUrl
from qgis.core import QgsProcessingAlgorithm, QgsApplication
from .OpenWeather_provider import OpenWeatherProvider
import processing
from .urls import DOC_PLUGIN_URL
cmd_folder = os.path.split(inspect.getfile(inspect.currentframe()))[0]

if cmd_folder not in sys.path:
    sys.path.insert(0, cmd_folder)


class OpenWeatherPlugin(object):

    def __init__(self,iface):
        self.provider = None
        self.iface = iface

    def initProcessing(self):
        """Init Processing provider for QGIS >= 3.8."""
        self.provider = OpenWeatherProvider()
        QgsApplication.processingRegistry().addProvider(self.provider)

    def initGui(self):
        self.initProcessing()
        icon = os.path.join(os.path.join(cmd_folder, 'weather.png'))
        self.action = QAction(
          QIcon(icon),
          u"OpenWeather Data (Current)", self.iface.mainWindow())
        self.action.triggered.connect(self.runn)
        self.iface.addPluginToMenu(u"&OpenWeather", self.action)
        self.iface.addToolBarIcon(self.action)
        
        icons = os.path.join(os.path.join(cmd_folder, 'air.png'))
        self.actionAide= QAction(QIcon(icons),u"OpenWeather Data (Historical)",self.iface.mainWindow())
        self.actionAide.triggered.connect(self.run)
        self.iface.addPluginToMenu(u"&OpenWeather", self.actionAide)
        self.iface.addToolBarIcon(self.actionAide)
        
        iconh = os.path.join(os.path.join(cmd_folder, 'help.png'))
        self.actionAideh= QAction(QIcon(iconh),u"help",self.iface.mainWindow())
        self.actionAideh.triggered.connect(self.showHelp)
        self.iface.addPluginToMenu(u"&OpenWeather", self.actionAideh)
        self.iface.addToolBarIcon(self.actionAideh)
    def unload(self):
        QgsApplication.processingRegistry().removeProvider(self.provider)
        self.iface.removePluginMenu(u"&OpenWeather", self.action)
        self.iface.removeToolBarIcon(self.action)
        
        self.iface.removePluginMenu(u"&OpenWeather", self.actionAide)
        self.iface.removeToolBarIcon(self.actionAide)
        
        self.iface.removePluginMenu(u"&OpenWeather", self.actionAideh)
        self.iface.removeToolBarIcon(self.actionAideh)
    def showHelp(self):  ### Help window
        QDesktopServices.openUrl(QUrl(DOC_PLUGIN_URL))
        
    def run(self):
        processing.execAlgorithmDialog("Open Weather Downloader:OpenWeather Data (Historical)")
        
    def runn(self):
        processing.execAlgorithmDialog("Open Weather Downloader:OpenWeather Data (Current)")